mean(Covid.Data[["x3"]]
max(Covid.DATA[["INTUBED"]])
max(Covid.Data[["INTUBED"]])     
min(Covid.Data[["INTUBED"]])
Select(Covid.Data, SEX)
library(dplyr)
select(Covid.Data, SEX)
count(Covid.Data, SEX)
table(Covid.Data$SEX) / length(Covid.Data$SEX)
colSums(is.na(Covid.Data)) 
